spring:
  application:
    name: notification-service
    activemq:
      broker-url: tcp://localhost:61616?wireFormat.maxInactivityDurationInitalDelay=30000
      user: admin
      password: admin


server:
  port: 8206