spring:
  application:
    name: booking-service
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
  activemq:
    broker-url: tcp://localhost:61616?wireFormat.maxInactivityDurationInitalDelay=30000
    user: admin
    password: admin



server:
  port: 8201
  error:
    include-message: always